name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Echo file
      run: |
        cat README.md

       # Install Git
    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Git branch
      run: |
        git branch

    - name: Print name
      run: |
        echo "This is a new file"